services:
  STACK_PLACEHOLDER-app:
    image: IMAGE_PLACEHOLDER
    environment:
    networks:
      - caddy
    deploy:
      replicas: 1
      labels:
        caddy: HOST_PLACEHOLDER
        caddy.tls: TLS_PLACEHOLDER
        caddy.reverse_proxy: "{{upstreams 3000}}" # important check same value on Dockerfile and PORT enviroment var

networks:
  caddy:
    external: true
